/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorycleaning.ui;
import inventorycleaning.dao.MaterialDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author spinn
 */
public class MaterialsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MaterialsPanel
     */
    public MaterialsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        materialsTable = new javax.swing.JTable();
        searchMaterialsField = new javax.swing.JTextField();
        searchMaterialsButton = new javax.swing.JButton();
        addMaterialsButton = new javax.swing.JButton();
        editMaterialsButton = new javax.swing.JButton();
        deleteMaterialsButton = new javax.swing.JButton();

        materialsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(materialsTable);

        searchMaterialsButton.setText("Search");
        searchMaterialsButton.addActionListener(this::searchMaterialsButtonActionPerformed);

        addMaterialsButton.setText("Add");

        editMaterialsButton.setText("Edit");
        editMaterialsButton.addActionListener(this::editMaterialsButtonActionPerformed);

        deleteMaterialsButton.setText("Delete");
        deleteMaterialsButton.addActionListener(this::deleteMaterialsButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addMaterialsButton)
                        .addGap(18, 18, 18)
                        .addComponent(editMaterialsButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteMaterialsButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchMaterialsField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchMaterialsButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchMaterialsField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMaterialsButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteMaterialsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addMaterialsButton)
                        .addComponent(editMaterialsButton))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchMaterialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMaterialsButtonActionPerformed
        MaterialDAO dao = new MaterialDAO();
        
        DefaultTableModel model = (DefaultTableModel) materialsTable.getModel();
        for(String[] row : dao.search(searchMaterialsField.getText())){
            model.addRow(row);
        }
    }//GEN-LAST:event_searchMaterialsButtonActionPerformed

    private void editMaterialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMaterialsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMaterialsButtonActionPerformed

    private void deleteMaterialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMaterialsButtonActionPerformed
        MaterialDAO dao = new MaterialDAO();
        
        dao.delete(searchMaterialsField.getText());
    }//GEN-LAST:event_deleteMaterialsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMaterialsButton;
    private javax.swing.JButton deleteMaterialsButton;
    private javax.swing.JButton editMaterialsButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable materialsTable;
    private javax.swing.JButton searchMaterialsButton;
    private javax.swing.JTextField searchMaterialsField;
    // End of variables declaration//GEN-END:variables
}
