package inventorycleaning.ui;

import inventorycleaning.dao.SupplierDAO;
import inventorycleaning.model.Supplier;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author spinn
 */
public class SuppliersPanel extends javax.swing.JPanel {

    private final SupplierDAO dao = new SupplierDAO();
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form SuppliersPanel
     */
    public SuppliersPanel() {
        initComponents();
        setupTable();
        loadSuppliers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliersTable = new javax.swing.JTable();
        searchSuppliersField = new javax.swing.JTextField();
        searchSuppliersButton = new javax.swing.JButton();
        addSuppliersButton = new javax.swing.JButton();
        editSuppliersButton = new javax.swing.JButton();
        deleteSuppliersButton = new javax.swing.JButton();

        suppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Contact Number", "Email"
            }
        ));
        jScrollPane1.setViewportView(suppliersTable);

        searchSuppliersButton.setText("Search");
        searchSuppliersButton.addActionListener(this::searchSuppliersButtonActionPerformed);

        addSuppliersButton.setText("Add");
        addSuppliersButton.addActionListener(this::addSuppliersButtonActionPerformed);

        editSuppliersButton.setText("Edit");
        editSuppliersButton.addActionListener(this::editSuppliersButtonActionPerformed);

        deleteSuppliersButton.setText("Delete");
        deleteSuppliersButton.addActionListener(this::deleteSuppliersButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addSuppliersButton)
                        .addGap(18, 18, 18)
                        .addComponent(editSuppliersButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteSuppliersButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchSuppliersField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchSuppliersButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchSuppliersField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSuppliersButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteSuppliersButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addSuppliersButton)
                        .addComponent(editSuppliersButton))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupTable() {
    tableModel = new DefaultTableModel(
        new Object[]{"ID", "Name", "Contact Number", "Email"}, 0  // 0 = start with zero rows
    ) {
        //prevent table editing from user
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    suppliersTable.setModel(tableModel);  // swap the dummy model for ours
}
    
    private void loadSuppliers() {
        populateTable(dao.getAll());
    }
    
    private void populateTable(List<Supplier> suppliers) {
        tableModel.setRowCount(0);
        for (Supplier s : suppliers) {
            tableModel.addRow(new Object[]{
                s.getId(), s.getName(), s.getContactNumber(), s.getEmail()
            });
        }
    }
    
    private void addSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuppliersButtonActionPerformed
        SupplierDialog dialog = new SupplierDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true
        );
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            boolean success = dao.insert(dialog.getSupplier());
            if (success) {
                loadSuppliers();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add supplier.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addSuppliersButtonActionPerformed

    private void editSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSuppliersButtonActionPerformed
        int row = suppliersTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a supplier to edit.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = (int) tableModel.getValueAt(row, 0);
        Supplier existing = dao.getById(id);
        System.out.println("Selected row id: " + id + ", fetched supplier: " + existing);
        if (existing == null) {
            JOptionPane.showMessageDialog(this, "Supplier not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SupplierDialog dialog = new SupplierDialog(
            (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, existing
        );
        dialog.setVisible(true);
        if (dialog.isSaved()) {
            //System.out.println("Updating supplier with id: " + dialog.getSupplier().toString());
            boolean success = dao.update(dialog.getSupplier());
            if (success) {
                loadSuppliers();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update supplier.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_editSuppliersButtonActionPerformed

    private void deleteSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSuppliersButtonActionPerformed
        int row = suppliersTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a supplier to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int id = (int) tableModel.getValueAt(row, 0);
        String name = (String) tableModel.getValueAt(row, 1);

        int confirm = JOptionPane.showConfirmDialog(
            this, "Delete supplier \"" + name + "\"?", "Confirm Delete", JOptionPane.YES_NO_OPTION
        );
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = dao.delete(id);
            if (success) {
                loadSuppliers();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete supplier.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteSuppliersButtonActionPerformed

    private void searchSuppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchSuppliersButtonActionPerformed
        String keyword = searchSuppliersField.getText().trim();
        if (keyword.isEmpty()) {
            loadSuppliers();
        } else {
            populateTable(dao.search(keyword));
        }
    }//GEN-LAST:event_searchSuppliersButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSuppliersButton;
    private javax.swing.JButton deleteSuppliersButton;
    private javax.swing.JButton editSuppliersButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchSuppliersButton;
    private javax.swing.JTextField searchSuppliersField;
    private javax.swing.JTable suppliersTable;
    // End of variables declaration//GEN-END:variables
}
